### ISSUE TITLE
Support for SQLite ???

### ISSUE THREAD

**Issue by JanSichula** [ampslive/AmpsBlog#7]
Hello,

as I am in search for some blog engine running on brand new ASP.NET Core 1.0, this project naturally caught my attention. But may I ask whether it will work with SQLite or PostgreSQL as we need to deploy on Linux VM. 

Keep on the good work with what seems to be a first ever ASP.NET Core blog engine. 

https://twitter.com/JanSichula

**Comment by ampslive** [comment]
Hi @JanSichula 

Thanks for your interest in this project. I was primarily looking to make it work on SQL Server but since SQLite is of interest to you, I think I can start simultaneously working towards it as well.

Thanks again :)

**Comment by JanSichula** [comment]
Hello,

thank you for your prompt response. Please, please implement support for SQLite and you will gain a very enthusiastic early adopter who will spread the news about your blog engine far and wide. :-)

P. S. We have several pending projects that we might possibly base on your blog engine including an all new web site for our independent Bible Baptist church.

One Bible quote for a contemplation:
"For God so loved the world, that He gave His only begotten Son, that whoever believes in Him shall not perish, but have eternal life.” John 3:16

**Comment by ampslive** [comment]
Hi @JanSichula 

I will try experimenting with Sqlite during this weekend and hopefully have good news for you soon.
Thanks for the verse, it is my personal favorite :)

**Comment by ampslive** [comment]
Hi @JanSichula 
I have got it to work on SQLite as well.

**Comment by JanSichula** [comment]
Thank you for all of your effort. Now that ASP.NET Core has RTMed, I am having a second look at your project. Do you plan to update it to RTM?

P. S. So happy to hear about you favorite Bible verse.
